// <auto-generated />
using BussinessObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BussinessObjects.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240603154850_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Assignment2.Models.MedicalFacility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityId"), 1L, 1);

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("NoDoctors")
                        .HasColumnType("int");

                    b.Property<int>("NoStaffs")
                        .HasColumnType("int");

                    b.Property<bool>("PrivateFacility")
                        .HasColumnType("bit");

                    b.HasKey("FacilityId");

                    b.ToTable("MedicalFacilities");

                    b.HasData(
                        new
                        {
                            FacilityId = 1,
                            FacilityName = "Green Valley Hospital",
                            Level = 4,
                            NoDoctors = 50,
                            NoStaffs = 200,
                            PrivateFacility = true
                        },
                        new
                        {
                            FacilityId = 2,
                            FacilityName = "Sunrise Health Center",
                            Level = 2,
                            NoDoctors = 30,
                            NoStaffs = 120,
                            PrivateFacility = false
                        },
                        new
                        {
                            FacilityId = 3,
                            FacilityName = "Lakeside Clinic",
                            Level = 1,
                            NoDoctors = 20,
                            NoStaffs = 80,
                            PrivateFacility = true
                        },
                        new
                        {
                            FacilityId = 4,
                            FacilityName = "Downtown Medical Center",
                            Level = 2,
                            NoDoctors = 40,
                            NoStaffs = 150,
                            PrivateFacility = false
                        },
                        new
                        {
                            FacilityId = 5,
                            FacilityName = "Riverside Hospital",
                            Level = 4,
                            NoDoctors = 60,
                            NoStaffs = 250,
                            PrivateFacility = true
                        },
                        new
                        {
                            FacilityId = 6,
                            FacilityName = "Mountainview Health Facility",
                            Level = 2,
                            NoDoctors = 25,
                            NoStaffs = 90,
                            PrivateFacility = false
                        },
                        new
                        {
                            FacilityId = 7,
                            FacilityName = "Oceanview Clinic",
                            Level = 5,
                            NoDoctors = 15,
                            NoStaffs = 60,
                            PrivateFacility = true
                        },
                        new
                        {
                            FacilityId = 8,
                            FacilityName = "City Central Hospital",
                            Level = 1,
                            NoDoctors = 55,
                            NoStaffs = 230,
                            PrivateFacility = false
                        },
                        new
                        {
                            FacilityId = 9,
                            FacilityName = "Hilltop Medical Center",
                            Level = 5,
                            NoDoctors = 35,
                            NoStaffs = 140,
                            PrivateFacility = true
                        },
                        new
                        {
                            FacilityId = 10,
                            FacilityName = "Valley View Hospital",
                            Level = 3,
                            NoDoctors = 45,
                            NoStaffs = 190,
                            PrivateFacility = false
                        });
                });

            modelBuilder.Entity("Assignment2.Models.ServicePriceList", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"), 1L, 1);

                    b.Property<int>("ServiceLevel")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ServicePrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ServiceId");

                    b.ToTable("ServicePriceLists");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            ServiceLevel = 1,
                            ServiceName = "General Consultation",
                            ServicePrice = 50.00m
                        },
                        new
                        {
                            ServiceId = 2,
                            ServiceLevel = 1,
                            ServiceName = "Basic Health Checkup",
                            ServicePrice = 75.00m
                        },
                        new
                        {
                            ServiceId = 3,
                            ServiceLevel = 2,
                            ServiceName = "Specialist Consultation",
                            ServicePrice = 120.00m
                        },
                        new
                        {
                            ServiceId = 4,
                            ServiceLevel = 2,
                            ServiceName = "Advanced Health Checkup",
                            ServicePrice = 150.00m
                        },
                        new
                        {
                            ServiceId = 5,
                            ServiceLevel = 3,
                            ServiceName = "Emergency Care",
                            ServicePrice = 200.00m
                        },
                        new
                        {
                            ServiceId = 6,
                            ServiceLevel = 3,
                            ServiceName = "Surgical Procedure",
                            ServicePrice = 500.00m
                        },
                        new
                        {
                            ServiceId = 7,
                            ServiceLevel = 4,
                            ServiceName = "Inpatient Care",
                            ServicePrice = 1000.00m
                        },
                        new
                        {
                            ServiceId = 8,
                            ServiceLevel = 4,
                            ServiceName = "Intensive Care",
                            ServicePrice = 2000.00m
                        },
                        new
                        {
                            ServiceId = 9,
                            ServiceLevel = 5,
                            ServiceName = "Specialized Surgery",
                            ServicePrice = 5000.00m
                        },
                        new
                        {
                            ServiceId = 10,
                            ServiceLevel = 5,
                            ServiceName = "Comprehensive Health Package",
                            ServicePrice = 10000.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
